spring:
  application:
    name: TWITTER-REST-SERVICE
    
server:
  port: 6061
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true
